### PR TITLE
Revert change for DEFAULT_JVM_OPTS

### PR DESCRIPTION
**Pull request by jabrena**
Revert change for DEFAULT_JVM_OPTS
Increase patch version

### CODE REVIEW

**Comment by JakubVanek** [comment]
This wasn't a manual removal by me - it happened when running:
```shell
/home/kuba/apps/gradle-5.6.1/bin/gradle wrapper
```
However it seems likely that the flags were added manually and the wrapper auto-upgrade scrapped them. In that case, they indeed should have remained there. I think this is the case and so I approve of this PR.

**Review by JakubVanek — APPROVED** [review]

**Comment by JakubVanek** [comment]
@jabrena why it is necessary to run Gradle with these flags? The library does not have them:
https://github.com/ev3dev-lang-java/ev3dev-lang-java/blame/master/gradlew#L31

**Comment by JakubVanek** [comment]
EDIT: my bad; the flags were *added* by the upgrade process...

**Comment by jabrena** [comment]
Tagged. I will create the PR for the rest of the projects

**Comment by JakubVanek** [comment]
Oki; however please base it off the latest upgrade PR branch, as there are sometimes fixes accompanying the plugin upgrades.

**Pull request merged**
